[project]
name = "nsw-campgrounds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "folium>=0.20.0",
    "requests>=2.32.5",
    "requests-cache>=1.2.1",
]
